WebPid.Web.Maintenance/Controllers/GlobalSettingsController.cs
using System;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using PagedList;
using WebPids.BusinessLogic;
using WebPids.Common;
using WebPids.EntityFramework;

namespace WebPids.Web.Maintenance.Controllers
{
    [Authorize]
    public class GlobalSettingsController : Controller
    {
        /// <summary>
        /// Main CRUD display
        /// </summary>
        /// <param name="currentFilter"></param>
        /// <param name="searchString"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            ViewBag.Message = "Following is the existing ticker message";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            using (var sp = ServiceProvider.CreateInstance)
            {
                var services = sp.GetService<GlobalSettingServices>();

                var data = services.GetAll();

                if (!string.IsNullOrEmpty(searchString))
                {
                    data = data.Where(s => s.Name.Contains(searchString));
                }

                var pageNumber = (page ?? 1);
                return View(data.ToList().ToPagedList(pageNumber, 4));
            }
        }
         

        /// <summary>
        /// Create a new display style object
        /// </summary>
        /// <returns>the view</returns>
        public ActionResult Create()
        {
            return PartialView("Create", new WebPids.EntityFramework.GlobalSetting());
        }

        /// <summary>
        /// Save the object to db
        /// </summary>
        /// <param name="model">the object</param>
        /// <returns>returns back to the root</returns>
        [HttpPost]
        public ActionResult CreateNew(GlobalSetting model)
        {
            using (var sp = ServiceProvider.CreateInstance)
            {
                var services = sp.GetService<GlobalSettingServices>();
                this.CallCrudMethod(services.Add, model);
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Open the edit page
        /// </summary>
        /// <param name="model">the object used</param>
        /// <returns>the page</returns>
        public ActionResult Edit(GlobalSetting model)
        {
            using (var sp = ServiceProvider.CreateInstance)
            {
                var services = sp.GetService<GlobalSettingServices>();

                // The default includes are missing from the model. Lets requery the db
                var obj = services.Get(model.Id);

                return PartialView("Edit", obj);
            }
        }

        /// <summary>
        /// Save the global setting
        /// </summary>
        /// <param name="model">the oject to save</param>
        /// <returns>the root page</returns>
        public ActionResult EditGlobalSetting(GlobalSetting model)
        {
            model.Value = model.Value ?? string.Empty;
            using (var sp = ServiceProvider.CreateInstance)
            {
                var services = sp.GetService<GlobalSettingServices>();
                this.CallCrudMethod(services.Update, model);
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Init the delete page
        /// </summary>
        /// <param name="model">the model to use</param>
        /// <returns>the delete page</returns>
        public ActionResult Delete(GlobalSetting model)
        {
            return PartialView("Delete", model);
        }

        /// <summary>
        /// Delete the object from db
        /// </summary>
        /// <param name="model">the model to use</param>
        /// <returns>back to root</returns>
        public ActionResult DeleteGlobalSetting(GlobalSetting model)
        {
            using (var sp = ServiceProvider.CreateInstance)
            {
                var services = sp.GetService<GlobalSettingServices>();
                this.CallCrudMethod(services.Delete, model);
                return RedirectToAction("Index");
            }
        }
    }
}

WebPid.Web.Maintenance/Views/GlobalSettings/Create.cshtml
@model WebPids.EntityFramework.GlobalSetting


<div class="modal-dialog">
    @using (Html.BeginForm("CreateNew", "GlobalSettings"))
    {
        @Html.AntiForgeryToken()
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>Create a Global Setting</h3>
            <hr />
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="modal-body">
            <fieldset>
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, "Name", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.EditorFor(model => model.Name, new { @class = "form-control" })
                    </div>
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.Value, "Value", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.EditorFor(model => model.Value, new { @class = "form-control" })
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Create New</button>
        </div>
    }
</div>


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

WebPid.Web.Maintenance/Views/GlobalSettings/Delete.cshtml
@model WebPids.EntityFramework.GlobalSetting

<div class="modal-dialog">
    @using (Html.BeginForm("DeleteGlobalSetting", "GlobalSettings"))
    {
        @Html.AntiForgeryToken()
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>Create a Display Style</h3>
            <hr />
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="modal-body">
            <fieldset>
                @Html.HiddenFor(model => model.Id)
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, "Name", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.Name)
                        @Html.HiddenFor(model => model.Name)
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.Value, "Description", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.Value)
                        @Html.HiddenFor(model => model.Value)
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Delete</button>
        </div>
    }
</div>


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

WebPid.Web.Maintenance/Views/GlobalSettings/Edit.cshtml
@model WebPids.EntityFramework.GlobalSetting


<div class="modal-dialog">
    @using (Html.BeginForm("EditGlobalSetting", "GlobalSettings", FormMethod.Post, new Dictionary<string, object>{{"id", "EditGlobalSettings"}}))
    {
        @Html.AntiForgeryToken()
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>Edit a Global Setting</h3>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="modal-body">
            <fieldset>
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.Name)
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Value, "Ticker Message", new { @class = "col-lg-2 control-label" })
                    <div class="col-lg-9">
                        @if (Model.Name == "GenericMessageEnabled")
                        {
                            bool genericMessageEnabledBool = Convert.ToBoolean(Model.Value);
                            @Html.CheckBoxFor(modelItem => genericMessageEnabledBool, new { @class = "form-control" })
                            @Html.HiddenFor(model => model.Value);
                        }
                        else if (Model.Name == "GenericMessage")
                        {
                            @Html.TextAreaFor(modelItem => modelItem.Value, new { @class = "form-control", @rows=10, @cols=50, @style="max-width:500px", @maxlength="200" })
                        }
                        else
                        {
                            @Html.EditorFor(model => model.Value, new {@class = "form-control"})
                        }

                    </div>
                </div>
            </fieldset>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="button" onclick="confirmUpdate()" class="btn btn-primary">Save</button>
        </div>
    }
</div>


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<script>
    function confirmUpdate() {
        if (confirm("Are you sure you wish to update setting[@Model.Name]?  They will be applied to all TSPIDs in the next fifteen seconds.")) {
            @if (Model.Name == "GenericMessageEnabled")
            {
                <text>
            if($('#genericMessageEnabledBool').prop('checked')){
                        $('#Value').attr('value', 'True');
                    }
                    else
                    {
                        $('#Value').attr('value', 'False');
                    }
                
                </text>
                
            }
            $("#EditGlobalSettings").submit();
            }
    }
</script>

WebPid.Web.Maintenance/Views/GlobalSettings/Index.cshtml
@{
    ViewBag.Title = "Train Station PID's Ticker Maintenance";
}
@using PagedList.Mvc
@model PagedList.IPagedList<WebPids.EntityFramework.GlobalSetting>


<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<table class="table table-striped table-hover fixed-table">
    <thead>
        <tr>
            <th>Ticker Message</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            if (obj.Name == "GenericMessageEnabled")
            {
                continue;
            }
            if (obj.Name == "ServiceUnavailableMessage")
            {
                continue;
            }
            if (obj.Name == "TestUrl")
            {
                ViewBag.TestUrl = obj.Value;
                continue;
            }
            
            <tr>
                <td class="wrap-td">@Html.DisplayFor(modelItem => obj.Value)</td>

                @if (!MvcApplication.IsUserReadOnly(User.Identity.Name))
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", "GlobalSettings", obj, new { @class = "modal-link btn btn-default" })
                    </td>
                }

            </tr>
        }
    </tbody>
</table>

<br />

<a href="@string.Format("{0}1",ViewBag.TestUrl)" target="_blank" onclick="window.open(this.href, 'Preview', 'resizable,left=100,top=100,width=1720,height=780'); return false;">View Production PID</a>