WebPid.Web.Maintenance/Controllers/PidsErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WebPids.BusinessLogic;
using WebPids.EntityFramework;
using System.Linq.Expressions;

namespace WebPids.Web.Maintenance.Controllers
{
    public class PidsErrorController : Controller
    {
        //
        // GET: /PidsError/
        public ActionResult Index(string searchString, string currentFilter)
        {
            Expression<Func<PidsElevatedLog,bool>> filter = null;
            if (!String.IsNullOrEmpty(searchString))
            {
                filter = x => x.ConfigurationId.ToString().Equals(searchString);
            }

            IEnumerable<PidsElevatedLog> errors;
            using (var sp = ServiceProvider.CreateInstance)
            {
                var service = sp.GetService<PidsElevatedLogServices>();
                errors = service.Get(filter, x => x.OrderByDescending(y => y.Id));
            }

            Session["Errors"] = errors;
            return View();
        }

        public PartialViewResult InitErrorList(int? pageNumber)
        {
            var model = Session["Errors"] as IEnumerable<PidsElevatedLog>;
            ViewBag.Errors = model.ToPagedList(pageNumber ?? 1, PidsElevatedLog.ErrorPageSize);
            return PartialView("ErrorList");
        }

        public ActionResult GetErrorList(int? pageNumber)
        {
            ViewBag.PageNumber = pageNumber;
            return View("Index");
        }
    }
}

WebPid.Web.Maintenance/Controllers/PidsHealthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WebPids.BusinessLogic;
using WebPids.EntityFramework;

namespace WebPids.Web.Maintenance.Controllers
{
    [Authorize]
    public class PidsHealthController : Controller
    {
        /// <summary>
        /// The max number of pids to display on this page
        /// </summary>

        /// <summary>
        /// Main page 
        /// </summary>
        /// <param name="sortColumn">column used for sorting</param>
        /// <param name="currentFilter">the filter</param>
        /// <param name="searchString">the search string</param>
        /// <returns>the main page</returns>
        public ActionResult Index(string sortColumn, string currentFilter, string searchString, string refreshRate)
        {

            if (searchString == null)
            {
                searchString = currentFilter;
            }

            UpdateViewBagParameters(sortColumn, searchString, refreshRate);


            var items = GetConfigurations(sortColumn, searchString);

            return View(items);
        }

        public ActionResult RefreshStatus(string sortColumn, string currentFilter, string searchString, string refreshRate)
        {
            UpdateViewBagParameters(sortColumn, searchString, refreshRate);
            return PartialView("HealthStatus", GetConfigurations(sortColumn, searchString));
        }

        public ActionResult Details(Configuration model)
        {
            // Load errors
            using (var sp = ServiceProvider.CreateInstance)
            {
                var service = sp.GetService<PidsElevatedLogServices>();
                model.Errors = service.GetByPidId(model.Id);
            } 
            return PartialView("Details", model);
        }

        #region Error List Methods

        public PartialViewResult InitErrorList(IEnumerable<PidsElevatedLog> model)
        {
            Session["Errors"] = model;
            ViewBag.Errors = model.ToPagedList(1, Configuration.ErrorPageSize);
            return PartialView("ErrorList");
        }

        public PartialViewResult GetErrorList(int? page)
        {
            var pageNumber = (page ?? 1);
            var model = Session["Errors"] as IEnumerable<PidsElevatedLog>;
            ViewBag.Errors = model.ToPagedList(pageNumber, Configuration.ErrorPageSize);

            return PartialView("ErrorList");
        }
        #endregion


        #region Private Methods

        private void UpdateViewBagParameters(string sortColumn, string searchString, string refreshRate)
        {
            ViewBag.LastUpdated = string.Format("PIDs Health Statuses at {0} on {1}", DateTime.Now.ToString("hh:mm tt"), DateTime.Now.ToString("dd/MM/yyyy"));
            ViewBag.CurrentFilter = searchString;

            ViewBag.CurrentSort = sortColumn;
            ViewBag.IdSortParm = "IdDesc";
            ViewBag.HealthStatusSortParam = "HealthStatusDesc";

            switch (sortColumn)
            {
                case "Id":
                    ViewBag.IdSortParm = "IdDesc";
                    break;
                case "IdDesc":
                    ViewBag.IdSortParm = "Id";
                    break;
                case "HealthStatus":
                    ViewBag.HealthStatusSortParam = "HealthStatusDesc";
                    break;
                case "HealthStatusDesc":
                    ViewBag.HealthStatusSortParam = "HealthStatus";
                    break;
            }

            if (refreshRate != null)
            {
                ViewBag.RefreshRate = refreshRate;
            }
            else
            {
                ViewBag.RefreshRate = 15000;
            }
        }

        private static IEnumerable<Configuration> GetConfigurations(string sortColumn, string searchString)
        {
            IEnumerable<Configuration> configList;
            using (var sp = ServiceProvider.CreateInstance)
            {
                var configurationServices = sp.GetService<ConfigurationServices>();
                var configurations = configurationServices.GetAllByHealthStatus();

                if (!String.IsNullOrEmpty(searchString) && searchString != HealthStatus.WildCard.Text)
                {
                    configurations = configurations.Where(s => s.HealthStatus.Text.Contains(searchString));
                }

                switch (sortColumn)
                {
                    case "IdDesc":
                        configurations = configurations.OrderByDescending(x => x.Id); 
                        break;
                    case "HealthStatus":
                        configurations = configurations.OrderBy(x => x.HealthStatus.Severity);
                        break;
                    case "HealthStatusDesc":
                        configurations = configurations.OrderByDescending(x => x.HealthStatus.Severity);
                        break;
                    default:
                        configurations = configurations.OrderBy(x => x.Id);
                        break;
                }
                
                configList = configurations.ToList();
            }
            return configList;
        }

        #endregion
    }
}

WebPid.Web.Maintenance/Controllers/PidsHistoryController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPids.BusinessLogic;
using WebPids.EntityFramework;
using WebPids.Web.Maintenance.ViewModels;

namespace WebPids.Web.Maintenance.Controllers
{
    [Authorize]
    public class PidsHistoryController : Controller
    {
        public IEnumerable<PidsElevatedLog> AllIncidents { get; private set; }
        //
        // GET: /PidsHistory/
        public ActionResult Index(string fromDateString, string toDateString, string network)
        {
            var dateFormatString = "dd/MM/yyyy";

            DateTime fromDate;
            DateTime toDate;
            bool showDayWeekMonth;

            var networkType = string.IsNullOrWhiteSpace(network) ? "all" : network;
            ViewBag.NetworkType = networkType;

            if (!(string.IsNullOrWhiteSpace(fromDateString) || string.IsNullOrWhiteSpace(toDateString)))
            {
                ViewBag.ShowDayWeekMonth = false;
                showDayWeekMonth = false;

                fromDate = DateTime.ParseExact(fromDateString, dateFormatString, CultureInfo.InvariantCulture);
                toDate = DateTime.ParseExact(toDateString, dateFormatString, CultureInfo.InvariantCulture).AddDays(1);
            }
            else
            {
                ViewBag.ShowDayWeekMonth = true;
                showDayWeekMonth = true;

                fromDate = DateTime.Today.AddDays(-30);
                toDate = DateTime.Today.AddDays(1);
            }

            ViewBag.FromDate = fromDate.ToString(dateFormatString);
            ViewBag.ToDate = toDate.ToString(dateFormatString);

            var items = GetPidHistoryDetails(fromDate, toDate, showDayWeekMonth, networkType);

            ViewBag.Pids = items.Select(x => string.Format("{0} - {1}", x.PidId, x.PidDescription));

            if (showDayWeekMonth)
            {
                ViewBag.Availability = items.Select(x => x.AvailabilityLastMonth);
                ViewBag.Incidents = items.Select(x => x.NumberOfIncidentsLastMonth);
            }
            else
            {
                ViewBag.Availability = items.Select(x => x.AvailabilityForDuration);
                ViewBag.Incidents = items.Select(x => x.NumberOfIncidentsForDuration);
            }

            return View(items);
        }

        private IEnumerable<PidHistoryViewModel> GetPidHistoryDetails(DateTime fromDate, DateTime toDate, bool showDayWeekMonth, string network)
        {
            var pidHistories = new List<PidHistoryViewModel>();
            var pids = new List<Configuration>();

            using (var sp = ServiceProvider.CreateInstance)
            {
                var service = sp.GetService<ConfigurationServices>();
                
                if (string.Equals(network, "all", StringComparison.OrdinalIgnoreCase))
                {
                    pids = service.GetAll().ToList();
                }
                else
                {
                    pids = service.Get(x => network.Equals(x.NetworkName, StringComparison.OrdinalIgnoreCase)).ToList();
                }

            }

            GetAllIncidents(fromDate, toDate);

            foreach (var pid in pids)
            {
                pidHistories.Add(GetHistoryForPid(pid, fromDate, toDate, showDayWeekMonth));
            }

            if (showDayWeekMonth)
            {
                return pidHistories.OrderByDescending(x => x.DownTimeLastMonth).ThenBy(x => x.PidId).ToList();
            }
            else
            {
                return pidHistories.OrderByDescending(x => x.DownTimeForDuration).ThenBy(x => x.PidId).ToList();
            }
        }

        private void GetAllIncidents(DateTime fromDate, DateTime toDate)
        {
            using (var sp = ServiceProvider.CreateInstance)
            {
                var service = sp.GetService<PidsElevatedLogServices>();
                AllIncidents = service.Get(x => x.Date >= fromDate && x.Date <= toDate && (x.DownTime > 0 || x.Message.Substring(0,7).Equals("OFFLINE", StringComparison.OrdinalIgnoreCase)));
            }
        }

        private PidHistoryViewModel GetHistoryForPid(Configuration pid, DateTime fromDate, DateTime toDate, bool showDayWeekMonth)
        {
            var pidIncidents = AllIncidents.Where(x => x.ConfigurationId == pid.Id);

            var pidHistory = new PidHistoryViewModel{PidId = pid.Id, PidDescription = string.Format("{0} - {1}", pid.StationName, pid.Description), IsEthernet = pid.NetworkName.Equals("Ethernet", StringComparison.OrdinalIgnoreCase)};

            if (showDayWeekMonth)
            {
                pidHistory.NumberOfIncidentsLastDay = GetNumberofIncidentsForPid(pidIncidents, DateTime.Today.AddDays(-1), DateTime.Today.AddDays(1));
                pidHistory.NumberOfIncidentsLastWeek = GetNumberofIncidentsForPid(pidIncidents, DateTime.Today.AddDays(-7), DateTime.Today.AddDays(1));
                pidHistory.NumberOfIncidentsLastMonth = GetNumberofIncidentsForPid(pidIncidents, DateTime.Today.AddDays(-30), DateTime.Today.AddDays(1));
                pidHistory.DownTimeLastDay = GetDowntimeMinutesForPid(pidIncidents, DateTime.Today.AddDays(-1), DateTime.Today.AddDays(1));
                pidHistory.DownTimeLastWeek = GetDowntimeMinutesForPid(pidIncidents, DateTime.Today.AddDays(-7), DateTime.Today.AddDays(1));
                pidHistory.DownTimeLastMonth = GetDowntimeMinutesForPid(pidIncidents, DateTime.Today.AddDays(-30), DateTime.Today.AddDays(1));
                pidHistory.AvailabilityLastDay = GetAvailability(pidHistory.DownTimeLastDay, DateTime.Today.AddDays(-1), DateTime.Today.AddDays(1));
                pidHistory.AvailabilityLastWeek = GetAvailability(pidHistory.DownTimeLastWeek, DateTime.Today.AddDays(-7), DateTime.Today.AddDays(1));
                pidHistory.AvailabilityLastMonth = GetAvailability(pidHistory.DownTimeLastMonth, DateTime.Today.AddDays(-30), DateTime.Today.AddDays(1));
            }
            else
            {
                pidHistory.NumberOfIncidentsForDuration = GetNumberofIncidentsForPid(pidIncidents, fromDate, toDate);
                pidHistory.DownTimeForDuration = GetDowntimeMinutesForPid(pidIncidents, fromDate, toDate);
                pidHistory.AvailabilityForDuration = GetAvailability(pidHistory.DownTimeForDuration, fromDate, toDate);
            }
            return pidHistory;
        }

        private int GetNumberofIncidentsForPid(IEnumerable<PidsElevatedLog> pidIncidents, DateTime fromDate, DateTime toDate)
        {
            int numberOfIncidents = pidIncidents.Where(x => x.Date >= fromDate && x.Date <= toDate).Count();
            return numberOfIncidents;
        }

        private int GetDowntimeMinutesForPid(IEnumerable<PidsElevatedLog> pidIncidents, DateTime fromDate, DateTime toDate)
        {
            /* TODO: 
             * Update this method to get add the latest outage duration if the PID is offline.
             * Check if the latest error starts with "OFFLINE".
             */
            int? outageMinutes;
            outageMinutes = pidIncidents.Where(x => x.Date >= fromDate && x.Date <= toDate && x.DownTime != null).Sum(y => y.DownTime);
            //Add the latest outage duration to outageMinutes here.
            return outageMinutes.HasValue ? outageMinutes.Value : 0;
        }

        private double GetAvailability(int downTime, DateTime fromDate, DateTime toDate)
        {
            double durationMinutes;
            if (toDate > DateTime.Today)
            {
                durationMinutes = DateTime.Now.Subtract(fromDate).TotalHours * 60;
            }
            else
            {
                durationMinutes = toDate.Subtract(fromDate).TotalHours * 60;
            }
            double availability = downTime > durationMinutes ? 0 : Math.Round((durationMinutes - downTime)/durationMinutes * 100, 2);
            return availability;
        }
    }
}

WebPid.Web.Maintenance/Views/Shared/_Layout.cshtml
@using System.Web.UI.WebControls
<!DOCTYPE html>
<html ng-app>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WebPIDs Maintenance Module</title>
    <base href="@Url.Content("~/")" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "navbar-brand" })</li>
                <li>@Html.ActionLink("Update Ticker", "Index", "GlobalSettings", null, new { @class = "navbar-brand" })</li>
                <li>@Html.ActionLink("PID Configuration", "Index", "PidsConfiguration", null, new { @class = "navbar-brand" })</li>
                <li>@Html.ActionLink("Audit Logs", "Index", "PidsActivity", null, new { @class = "navbar-brand" })</li>
                <li>@Html.ActionLink("PID Health", "Index", "PidsHealth", null, new { @class = "navbar-brand" })</li>
                <li>@Html.ActionLink("PID History Report", "Index", "PidsHistory", null, new { @class = "navbar-brand" })</li>
                <li>@Html.ActionLink("PID Errors", "Index", "PidsError", null, new { @class = "navbar-brand" })</li>
                <li><a href="http://10.0.205.21:8980/opennms/login.jsp" target="_blank" class="navbar-brand" title="Metromatics openNMS">PID Hardware</a></li>
            </ul>
            <p class="nav navbar-text navbar-right">Welcome, @User.Identity.Name</p>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        @if (!@MvcApplication.IsUserReadOnly(@User.Identity.Name))
        {
            <p>You are connected to database @MvcApplication.DatabaseName</p>
            <p>This website requires Chrome browser.</p>
        }
        else
        {
            <p>You are connected to database @MvcApplication.DatabaseName in <b>readonly</b> mode</p>
        }
    </footer>
</div>


<div id="modal-container" class="modal fade"
     tabindex="-1" role="dialog">
    <div class="modal-content">
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/highcharts")
@Scripts.Render("~/bundles/zingchart")
@RenderSection("scripts", required: false)
</body>
</html>
<script type="text/javascript">
    $(function () {
        // Initialize modal dialog
        // attach modal-container bootstrap attributes to links with .modal-link class.
        // when a link is clicked with these attributes, bootstrap will display the href content in a modal dialog.
        $("body").on("click", ".modal-link", function (e) {
            e.preventDefault();
            $(this).attr("data-target", "#modal-container");
            $(this).attr("data-toggle", "modal");
            $(this).attr("data-backdrop", "static");
            $(this).attr("data-keyboard", "false");
        });
        // Attach listener to .modal-close-btn's so that when the button is pressed the modal dialog disappears
        $("body").on("click", ".modal-close-btn", function () {
            $("#modal-container").modal("hide");
        });

        //clear modal cache, so that new content can be loaded
        $("#modal-container").on("hidden.bs.modal", function () {
            $(this).removeData("bs.modal");
        });
        $("#CancelModal").on("click", function () {
            return false;
        });
    });
</script>