WebPid.Web.Maintenance/Controllers/PidsConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Web.Mvc; 
using PagedList;
using WebPids.EntityFramework;
using WebPids.BusinessLogic;
using WebPids.Common;

namespace WebPids.Web.Maintenance.Controllers
{
    /// <summary>
    /// The PIDs CRUD
    /// </summary>
    [Authorize]
    public class PidsConfigurationController : Controller
    {
        /// <summary>
        /// The max number of configs to display on this page
        /// </summary>
        private const int ConfigPageSize = 5;
        private const string testUrl = "TestUrl";
 
        #region Configuration CRUD
        /// <summary>
        /// Main page 
        /// </summary>
        /// <param name="sortColumn">column used for sorting</param>
        /// <param name="currentFilter">the filter</param>
        /// <param name="searchString">the search string</param>
        /// <param name="page">the current page</param>
        /// <returns>the main page</returns>
        public ActionResult Index(string sortColumn, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortColumn;
            ViewBag.Message = "Following are the existing Configurations";

            ViewBag.IdSortParm = String.IsNullOrEmpty(sortColumn) ? "Id desc" : "";
            ViewBag.StationNameSortParm = sortColumn == "StationName" ? "StationName desc" : "StationName";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            using (var sp = ServiceProvider.CreateInstance)
            {
                var services = sp.GetService<GlobalSettingServices>();
                var baseDisplayUrl = services.GetValByName(testUrl);

                var configurationServices = sp.GetService<ConfigurationServices>();
                var configurations = configurationServices.GetAllWithHealth();

                foreach (var item in configurations)
                {
                    item.BaseDisplayUrl = baseDisplayUrl;
                }

                if (!String.IsNullOrEmpty(searchString))
                {
                    configurations = configurations.Where(s => s.StationName.ToLower().Contains(searchString.ToLower()));
                }

                switch (sortColumn)
                {
                    case "Id desc":
                        configurations = configurations.OrderByDescending(s => s.Id);
                        break;
                    case "StationName":
                        configurations = configurations.OrderBy(s => s.StationName);
                        break;
                    case "StationName desc":
                        configurations = configurations.OrderByDescending(s => s.StationName);
                        break;
                    default:
                        configurations = configurations.OrderBy(s => s.Id);
                        break;
                }

                return View(configurations.ToList());
            }
        }

        /// <summary>
        /// Create page
        /// </summary>
        /// <returns>the page with a new model object</returns>
        public ActionResult Create()
        {
            var configuration = new Configuration() {NumOfLines = 3};
            return PartialView("Create", configuration);
        }

        /// <summary>
        /// Create a new config record and return back to root
        /// </summary>
        /// <param name="model">the model to save</param>
        /// <returns>the root page</returns>
        public ActionResult CreateNew(Configuration model)
        {
            model.MonitorHeartBeat = true;
            model.PIDName = string.Empty;
            model.DirectionsId = 1;

            using (var sp = ServiceProvider.CreateInstance)
            {
                var configurationServices = sp.GetService<ConfigurationServices>();
                if (ModelState.IsValid)
                {
                    this.CallCrudMethod(configurationServices.Add, model);
                }

                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Display the edit page
        /// </summary>
        /// <param name="model">the model</param>
        /// <returns>contents of the edit page</returns>
        public ActionResult Edit(Configuration model)
        {
            using (var sp = ServiceProvider.CreateInstance)
            {
                var configurationServices = sp.GetService<ConfigurationServices>();
                // The default includes are missing from the model. Lets requery the db
                var obj = configurationServices.GetConfiguration(model.Id);
                return PartialView("Edit", obj);
            }
        }

        /// <summary>
        /// Save the configuration
        /// </summary>
        /// <param name="model">the object ot save</param>
        /// <returns>the root</returns>
        [HttpPost]
        public ActionResult EditConfiguration(Configuration model)
        {
            model.PIDName = string.Empty;

            using (var sp = ServiceProvider.CreateInstance)
            {
                var configurationServices = sp.GetService<ConfigurationServices>();
                this.CallCrudMethod(configurationServices.Update, model);

                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Display the delete page
        /// </summary>
        /// <param name="model">the model to use</param>
        /// <returns>the delete page</returns>
        public ActionResult Delete(Configuration model)
        {
            return PartialView("Delete", model);
        }

        /// <summary>
        /// Display the details page
        /// </summary>
        /// <param name="model">the model to use</param>
        /// <returns>the details page</returns>
        public ActionResult Detail(Configuration model)
        {
            return PartialView("Detail", model);
        }

        /// <summary>
        /// Delete a configuration
        /// </summary>
        /// <param name="model">the model to delete</param>
        /// <returns>the root</returns>
        public ActionResult DeleteConfiguration(Configuration model)
        {
            using (var sp = ServiceProvider.CreateInstance)
            {
                var configurationServices = sp.GetService<ConfigurationServices>();
                configurationServices.Delete(model);
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region Stops list methods
        /// <summary>
        /// Initialize the stops list partial view 
        /// </summary>
        /// <param name="model">the stops to populate</param>
        /// <returns>the stopslist view</returns>
        public PartialViewResult InitStopsList(IEnumerable<Stop> model)
        {
            ViewBag.Stops = model;
            return PartialView("StopsList");
        }

        #endregion

        #region Stops CRUD
        /// <summary>
        /// Init the create stops control  
        /// </summary>
        /// <param name="configurationId">the config id</param>
        /// <returns>the control</returns>
        public ActionResult RenderCreateStop(long configurationId)
        {
            return PartialView("CreateStop", new Stop() {ConfigurationId = configurationId});
        }

        /// <summary>
        /// Crate a new stop
        /// </summary>
        /// <param name="model">the model</param>
        /// <returns>error or success</returns>
        [HttpPost]
        public ActionResult CreateNewStop(Stop model)
        {
            using (var sp = ServiceProvider.CreateInstance)
            {
                var stopServices = sp.GetService<StopServices>();
                return this.CallCrudMethod(stopServices.Add, model);
            }
        }

        /// <summary>
        /// Init the edit stops control
        /// </summary>
        /// <returns>the control</returns>
        public ActionResult RenderEditStop()
        {
            return PartialView("EditStop", new Stop());
        }

        /// <summary>
        /// Open the edit stops control
        /// </summary>
        /// <param name="model">the model used to populate</param>
        /// <returns>the control</returns>
        public ActionResult EditStop(Stop model)
        {
            using (var sp = ServiceProvider.CreateInstance)
            {
                var stopServices = sp.GetService<StopServices>();
                var stop = stopServices.GetStopById(model.Id);
                return PartialView("EditStop", stop);
            }
        }

        /// <summary>
        /// Same the stop in db
        /// </summary>
        /// <param name="model">the object</param>
        /// <returns>error or success</returns>
        [HttpPost]
        public ActionResult UpdateStop(Stop model)
        {
            using (var sp = ServiceProvider.CreateInstance)
            {
                var stopServices = sp.GetService<StopServices>();
                return this.CallCrudMethod(stopServices.Update, model);
            }
        }

        /// <summary>
        /// Init the delete stop control
        /// </summary>
        /// <returns>the control</returns>
        public PartialViewResult RenderDeleteStop()
        {
            return PartialView("DeleteStop", new Stop());
        }

        /// <summary>
        /// Open the delete stop control with a object
        /// </summary>
        /// <param name="model">the object</param>
        /// <returns>the control</returns>
        public ActionResult DeleteStop(Stop model)
        {
            return PartialView("DeleteStop", model);
        }

WebPid.Web.Maintenance/Views/PIDSConfiguration/Create.cshtml
@model WebPids.EntityFramework.Configuration
 

<div class="modal-dialog">
    @using (Html.BeginForm("CreateNew", "PidsConfiguration", FormMethod.Post, new { id = "createConfigForm" }))
    {
        @Html.AntiForgeryToken()
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>Create a PIDS Configuration</h3>
            <hr/>
        </div>
                
        <div class="modal-body">
                <fieldset>
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group">
                        @Html.LabelFor(model => model.Id, "PID Id", new { @class = "col-lg-6 control-label", @title = "Unique PID Number for the TSPID application" })
                        <div class="col-lg-6">
                            @Html.Label(Model.Id.ToString(), new { @class = "col-lg-6 control-label" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.StationName, "Station Name", new { @class = "col-lg-6 control-label", @title = "Street upon which the tram stop is located" })
                        <div class="col-lg-6">
                            @Html.TextBoxFor(model => model.StationName, new { @class = "form-control fixed-size-control", @title = "Street upon which the tram stop is located" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.PIDAssetLocationNo, "PID Asset Location No", new { @class = "col-lg-6 control-label" })
                        <div class="col-lg-6">
                            @Html.TextBoxFor(model => model.PIDAssetLocationNo, new { @class = "form-control fixed-size-control" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, "PID Location", new { @class = "col-lg-6 control-label", @title = "Location of the physical PID eg. Swanston Street/Prince Bridge exit" })
                        <div class="col-lg-6">
                            @Html.TextBoxFor(model => model.Description, new { @class = "form-control fixed-size-control", @title = "Location of the physical PID eg. Swanston Street/Prince Bridge exit" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.NetworkName, "Network Connectivity", new { @class = "col-lg-6 control-label" })
                        <div>
                            @Html.DropDownListFor(model => model.NetworkName, Model.GetNetworkNames(), new { @class = ".fixed-length-input" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.DisplayOrderId, "Display Order", new { @class = "col-lg-6 control-label" })
                        <div>
                            @Html.DropDownListFor(model => model.DisplayOrderId, new SelectList(Model.GetDisplayOrders(), "Id", "Name"))
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.OrientationMode, "Orientation (Note this value is manually configured on PID by ICT-Dev team.)", new { @class = "col-lg-6 control-label" })
                        <div>
                            @Html.DropDownListFor(model => model.OrientationMode, new SelectList(Model.GetOrientationModes()))
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.Enabled, "Enabled?", new {@class = "col-lg-6 control-label"})
                        <div>
                            @Html.EditorFor(model => model.Enabled, new { @class = "form-control" })
                        </div>
                    </div>
                </fieldset>
        </div>
        <div class="modal-footer">
            @*<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>*@
            <button type="button" class="btn btn-default" onclick=" cancel('createConfigForm'); ">Cancel</button>
            <button type="submit" class="btn btn-primary">Create New</button>
        </div>
    }
</div>


@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>*@
<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    // cancel or close the dialog
    function cancel(dialogname) {
        $("#" + dialogname).modal("hide");
    }
</script>

WebPid.Web.Maintenance/Views/PIDSConfiguration/Delete.cshtml
@model WebPids.EntityFramework.Configuration


<div class="modal-dialog">
    @using (Html.BeginForm("DeleteConfiguration", "PidsConfiguration"))
    {
        @Html.AntiForgeryToken()
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>Are you sure you want to delete the following PIDS Configuration?</h3>
        </div>

        <div class="modal-body">
            <fieldset>
                @Html.HiddenFor(model => model.Id)
                <div class="form-group">
                    @Html.LabelFor(model => model.Id, "PID Id", new { @class = "col-lg-6 control-label", @title = "Unique PID Number for the TSPID application" })
                    <div class="col-lg-6">
                        @Html.Label(Model.Id.ToString())
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.StationName, "Station Name", new { @class = "col-lg-6 control-label", @title = "Street upon which the tram stop is located" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.StationName, new { @title = "Street upon which the tram stop is located" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.PIDAssetLocationNo, "PID Asset Location No", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.PIDAssetLocationNo)
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, "PID Location", new { @class = "col-lg-6 control-label", @title = "Location of the physical PID eg. Swanston Street/Prince Bridge exit" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.Description, new { @title = "Location of the physical PID eg. Swanston Street/Prince Bridge exit" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.NetworkName, "Network Name", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.NetworkName)
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.OrientationMode, "Orientation", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.OrientationMode)
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Delete</button>
        </div>
    }
</div>

WebPid.Web.Maintenance/Views/PIDSConfiguration/Detail.cshtml
@model WebPids.EntityFramework.Configuration


<div class="modal-dialog">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>PIDS Configuration</h3>
            <hr />
        </div>

        <div class="modal-body">
            <fieldset>
                @Html.HiddenFor(model => model.Id)
                <div class="form-group">
                    @Html.LabelFor(model => model.PIDName, "PID Name", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.PIDName)
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, "Description", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.Description)
                    </div>
                </div>
                <br/>
                <div class="form-group">
                    @Html.LabelFor(model => model.NetworkName, "Network Name", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.NetworkName)
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.OrientationMode, "Orientation", new { @class = "col-lg-6 control-label" })
                    <div class="col-lg-6">
                        @Html.DisplayFor(model => model.OrientationMode)
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    }
</div>


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

WebPid.Web.Maintenance/Views/PIDSConfiguration/Edit.cshtml
@model WebPids.EntityFramework.Configuration

<div class="modal-dialog" id="editConfigurationDlg">
    @using (Html.BeginForm("EditConfiguration", "PidsConfiguration", FormMethod.Post, new { id = "editConfigurationForm" }))
    {
            <div class="modal-header">
                <h4 class="modal-title">Modify a PIDS Configuration</h4>
            </div>

            @Html.HiddenFor(model => model.MonitorHeartBeat)
            @Html.HiddenFor(model => model.HeartbeatLastUpdatedTime)
            @Html.HiddenFor(model => model.MonitorPageProcessing)
            @Html.HiddenFor(model => model.PageProcessingTimeTaken)

            <div class="modal-body">
                <fieldset>
                    <div id="errorSummary" class="validation-summary-errors text-danger" />
                    <br />
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.PIDName)
                    @Html.HiddenFor(model => model.Distance)
                    @Html.HiddenFor(model => model.DirectionsId)
                    <div class="form-group">
                        @Html.LabelFor(model => model.Id, "PID Id", new { @class = "col-lg-6 control-label", @title = "Unique PID Number for the TSPID application" })
                        <div class="col-lg-6">
                            @Html.Label(Model.Id.ToString(), new { @class = "col-lg-6 control-label" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.StationName, "Station Name", new { @class = "col-lg-6 control-label", @title = "Street upon which the tram stop is located" })
                        <div class="col-lg-6">
                            @Html.TextBoxFor(model => model.StationName, new { @class = "form-control fixed-size-control", @title = "Street upon which the tram stop is located", @maxlength = "50" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.PIDAssetLocationNo, "PID Asset Location No", new { @class = "col-lg-6 control-label" })
                        <div class="col-lg-6">
                            @Html.TextBoxFor(model => model.PIDAssetLocationNo, new { @class = "form-control fixed-size-control", @maxlength = "15" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.VicTrackId, "VicTrack ID", new { @class = "col-lg-6 control-label" })
                        <div class="col-lg-6">
                            @Html.TextBoxFor(model => model.VicTrackId, new { @class = "form-control fixed-size-control", @maxlength = "14" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, "PID Location", new { @class = "col-lg-6 control-label", @title = "Location of the physical PID eg. Swanston Street/Prince Bridge exit" })
                        <div class="col-lg-6">
                            @Html.TextBoxFor(model => model.Description, new { @class = "form-control fixed-size-control", @title =  Model.Description, @maxlength = "5000" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.NetworkName, "Network Connectivity", new { @class = "col-lg-6 control-label" })
                        <div>
                            @Html.DropDownListFor(model => model.NetworkName, Model.GetNetworkNames(), new { @class = ".fixed-length-input" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.DisplayOrderId, "Display Order", new { @class = "col-lg-6 control-label" })
                        <div>
                            @Html.DropDownListFor(model => model.DisplayOrderId, new SelectList(Model.GetDisplayOrders(), "Id", "Name"))
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.OrientationMode, "Orientation (Note this value is manually configured on PID by ICT-Dev team.)", new { @class = "col-lg-6 control-label" })
                        <div>
                            @Html.DropDownListFor(model => model.OrientationMode, new SelectList(Model.GetOrientationModes()))
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.Enabled, "Enabled?", new {@class = "col-lg-6 control-label"})
                        <div>
                            @Html.EditorFor(model => model.Enabled, new { @class = "form-control" })
                        </div>
                    </div>
                    
                    <br />
                    <div id="stopsCtrl">
                        @{
                            Html.RenderAction("InitStopsList", "PidsConfiguration", new {model = Model.Stops});
                        }
                    </div>
                </fieldset>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cancelConfig">Cancel</button>
                <button type="submit" class="btn btn-primary" id="saveConfig">Save</button>
            </div>
    }
</div>

<div class="modal fade" id="createStop" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    @{
        Html.RenderAction("RenderCreateStop", "PidsConfiguration", new { ConfigurationId = @Model.Id });
    }
</div>


<div class="modal fade" id="editStop" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    @{
        Html.RenderAction("RenderEditStop", "PidsConfiguration");
    }
</div>

<div class="modal fade" id="deleteStop" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    @{
        Html.RenderAction("RenderDeleteStop", "PidsConfiguration");
    }
</div>


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        // Invoke to create a new stop in db
        $("#createNewStop").click(function (e) {
            var url = getBaseUrl(document.location) + "/CreateNewStop";
            var valid = $("#createStopForm").valid();
            if (valid) {
                var htmldata;
                $.ajax({
                    url: url,
                    type: "POST",
                    async: false,
                    data: $("#createStopForm").serialize()
                });

                url = getBaseUrl(document.location) + "/Edit";
                // get the edit config dialog html
                $.ajax({
                    url: url,
                    type: "GET",
                    data: $("#editConfigurationForm").serialize(),
                    async: false,
                    success: function (result) {
                        htmldata = result;
                    }
                });

                // repaint screen
                cancel("createStop");
                $("#editConfigurationDlg").html(htmldata);
                $("#editConfigurationDlg").find(".modal-backdrop").remove();
            }

            return false;
        });

        // Save an existing config
        $("#saveConfig").click(function (e) {
            //debugger;
            var valid = $("#editConfigurationForm").valid();
            if (valid) {
                $("#errorSummary").html("");
                var url = getBaseUrl(document.location) + "/EditConfiguration";
                // perform operation
                $.ajax({
                    url: url,
                    type: "POST",
                    async: false,
                    data: $("#editConfigurationForm").serialize(),
                    success: function () {
                        // reload parent
                        location.reload(true);
                    }
                });
            }
            else {
                // Show error
                $("#errorSummary").html("Please enter correct values for all fields before saving.");
            }


            return false;
        });

        // Cancel an existing config
        $("#cancelConfig").click(function (e) {
            location.reload(true);
            return false;
        });
    });

    function getBaseUrl(location) {
        return location.href.replace(location.search, "");
    }

    // cancel or close the dialog
    function cancel(dialogname) {
        $("#" + dialogname).modal("hide");
    }

    // close the dialog on validation
    function commit(dialogname) {
        if ($("#" + dialogname).$valid)
        {
            $("#" + dialogname).modal("hide");
        } else
        {
            return true;
        }
    }

    // launch the dialog
    function launch_modal(dialogname) {
        $("#" + dialogname).modal("show");
    }
     
    // delete the stop
    function onDeleteStop() {
        var valid = $("#deleteStopForm").valid();
        if (valid) {
            var htmldata;
            var url = getBaseUrl(document.location) + "/RemoveStop";

            // perform operation
            $.ajax({
                url: url,
                type: "POST",
                async: false,
                data: $("#deleteStopForm").serialize()
            });

            url = getBaseUrl(document.location) + "/Edit";

            // get parent screen data
            $.ajax({
                url: url,
                type: "GET",
                data: $("#editConfigurationForm").serialize(),
                async: false,
                success: function (result) {
                    htmldata = result;
                }
            });

            // refresh screen
            cancel("deleteStop");
            $("#editConfigurationDlg").html(htmldata);
            $("#editConfigurationDlg").find(".modal-backdrop").remove();
        }
    }

</script>